# Generated by Django 3.2.22 on 2023-10-29 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=30)),
                ('task_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('attachments', models.FileField(null=True, upload_to='')),
                ('link', models.URLField(null=True)),
                ('homework_tasks', models.ManyToManyField(to='lms.HomeworkTask')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=25)),
                ('available_from', models.DateTimeField(default=datetime.datetime(2023, 10, 29, 15, 31, 36, 40060))),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.course')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.homework')),
            ],
            options={
                'unique_together': {('title', 'course')},
            },
        ),
    ]
