# Generated by Django 3.2.22 on 2023-10-29 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
