# Generated by Django 3.2.22 on 2023-11-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20231119_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
