# Generated by Django 3.2.22 on 2023-11-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_auto_20231126_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
