# Generated by Django 3.2.22 on 2023-11-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_homeworksubmission_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
