# Generated by Django 3.2.22 on 2023-10-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'teacher'), ('STUDENT', 'student')], default='STUDENT', max_length=25),
        ),
    ]
