version: '3.8'

services:

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - lms_net
    env_file:
      - .env
    ports:
      - 5433:5432

  nginx:
    restart: always
    networks:
      - lms_net
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx-build
    volumes:
      - ./nginx/:/etc/nginx/conf.d:ro
    ports:
      - "${ANGULAR_DJANGO_HTTP_PORT:-80:80}"

  angular:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: angular-demo-build

  gunicorn:
    restart: always
    networks:
      - lms_net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build:
      context: ./backend/pythonlms
      dockerfile: ./Dockerfile
    volumes:
      - media_data:/app/uploads
    env_file:
      - .env






volumes:
  postgres_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/db_data
      o: bind
  media_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/media_data
      o: bind


networks:
  lms_net:
    external: true
